server:
  port: 9002
spring:
  application:
    name: hrm-course
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hrm_sysmanage
      username: root
      password: 335243
mybatis-plus:
  mapper-locations: classpath:com/xurui/hrm/mapper/*Mapper.xml
  type-aliases-package: com.xurui.hrm.domain,com.xurui.hrm.query
